
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_ABRE = 7;
  public static final int PUNTO = 9;
  public static final int CADENA = 22;
  public static final int LLAVE_CIERRA = 8;
  public static final int OR = 10;
  public static final int SUMA = 12;
  public static final int RCONJ = 2;
  public static final int FLECHA = 4;
  public static final int PALITO = 6;
  public static final int DOS_PUNTOS = 3;
  public static final int PORCENTAJE = 14;
  public static final int CARACTER = 21;
  public static final int COMA = 5;
  public static final int NOMBRE = 17;
  public static final int EOF = 0;
  public static final int ASTERISCO = 11;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 16;
  public static final int PREGUNTA = 13;
  public static final int PUNTO_COMA = 15;
  public static final int ASCII = 20;
  public static final int ENTERO = 19;
  public static final int NOMBRE_M = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RCONJ",
  "DOS_PUNTOS",
  "FLECHA",
  "COMA",
  "PALITO",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "PUNTO",
  "OR",
  "ASTERISCO",
  "SUMA",
  "PREGUNTA",
  "PORCENTAJE",
  "PUNTO_COMA",
  "IDENTIFICADOR",
  "NOMBRE",
  "NOMBRE_M",
  "ENTERO",
  "ASCII",
  "CARACTER",
  "CADENA"
  };
}

